redis:
    image: redis
    container_name: cache
    expose:
      - 6379
app:
    build: ./
    volumes:
        - ./:/usr/src/app
    links:
        - redis
    ports:
        - 5000:5000
    environment:
        - REDIS_URL=redis://cache
        - NODE_ENV=development
        - PORT=5000
    command:
        sh -c 'npm i && node api/index.js'